# -------------------------
#        ALIASES
# -------------------------
aliases:
  # -------------------------
  #      ALIASES: Caches
  # -------------------------
  - &restore-yarn-cache
    keys:
      - v1-yarn-cache-{{ arch }}-{{ checksum "yarn.lock" }}
      - v1-yarn-cache-{{ arch }}

  - &save-yarn-cache
    paths:
      - ~/.cache/yarn
    key: v1-yarn-cache-{{ arch }}-{{ checksum "yarn.lock" }}


# -------------------------
#          JOBS
# -------------------------
version: 2
jobs:
  test:
    docker:
      - image: node:6
    working_directory: ~/idx
    steps:
      - checkout
      - restore-cache: *restore-yarn-cache
      - run: yarn install --non-interactive --cache-folder ~/.cache/yarn
      - save-cache: *save-yarn-cache
      - run: yarn test
      - run: yarn lint

# -------------------------
#        WORK FLOWS
# -------------------------
workflows:
  version: 2

  tests:
    jobs:
      - test
